jobs:
 - name: u16ruball
   type: runSh
   runtime:
     container: true
   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16ruball"
             imageTag: master
         script:
          - source /etc/profile.d/rvm.sh
          - rvm list
          - ruby --version
